name: Publish bitgo api release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  package:
    name: Package Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate metadata for Docker
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: jgrancell/bitgo
          flavor: |
            latest=true

      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - uses: docker/build-push-action@v2
        name: Build and Push
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
  validate:
    name: Package::Validate
    runs-on: ubuntu-latest
    services:
      bitgo:
        image: jgrancell/bitgo:latest
        ports:
          - 8080:8080
    steps:
      - name: Check health endpoint
        run: curl http://localhost:8080/healthz
      - name: Check USD currency
        run: curl http://localhost:8080/usd | jq .amount
#  deploy:
#    name: Deploy New Release
#    runs-on: ubuntu-latest
#    needs: 
#      - package
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v1
#        working-directory: ./deploy/terraform
#
#      - name: Teraform Init
#        run: terraform init
#        working-directory: ./deploy/terraform
#
#      - name: Terraform Apply
#        run: terraform apply -auto-approve
#        working-directory: ./deploy/terraform
#        with:
#          argocd_auth_token: ${{secrets.ARGOCD_AUTH_TOKEN}}